name: pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches:  none # [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-test:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: actions-test
      TAGS: dev
    
    steps:

    - name: Git Checkout
      uses: actions/checkout@v3
    
    # Runs Sonar scanner on code base
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master

    # Run Cypress Test
    - name: Run Cypress Test
      uses: cypress-io/github-action@v4
      with:
        command: npx cypress run
        browser: chrome

    # Setup S2i and Build container image
    - name: Setup and Build
      id: build_image
      uses: redhat-actions/s2i-build@v2
      with:
        path_context: '.'
        # Builder image for a node project
        builder_image: 'centos/nodejs-10-centos7'
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.TAGS }}

    # Push Image to Quay registry
    - name: Push To Quay Action
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: quay.io/${{ secrets.QUAY_USERNAME }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        image-ref: 'quay.io/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAGS }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'MEDIUM,HIGH,CRITICAL'
